server:
  port: 4001

spring:
  application:
    name: pig-config-server
  cloud:
    config:
      server:
        git:
          uri: https://www.gitee.wang/a/pig-config.git
    bus:
      trace:
        enabled: true
#  rabbitmq:
#    host: 192.168.1.122
#    port: 5682
#    username: guest
#    password: guest
#    virtual-host: /

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://pig:gip6666@localhost:1001/eureka

