version: '2'
services:
  pig-eureka:
    build:
      context: ./
      dockerfile: Dockerfile-eureka
    restart: always
    ports:
      - 59025:1025

  pig-config:
    build:
      context: ./
      dockerfile: Dockerfile-config
    restart: always

  pig-gateway:
    build:
      context: ./
      dockerfile: Dockerfile-gateway
    restart: always
    ports:
      - 59999:9999

  pig-auth:
    build:
      context: ./
      dockerfile: Dockerfile-auth
    restart: always

  pig-upms-service:
    build:
      context: ./
      dockerfile: Dockerfile-upms
    restart: always